
apiVersion: apps/v1
kind: Deployment
metadata:
    name: c2
    labels:
      app: c2
spec:
    replicas: 1
    selector:
        matchLabels:
            app: c2
    template:
        metadata:
            labels:
                app: c2
        spec:
            dnsConfig:
              nameservers:
                - 8.8.8.8
            volumes:
            containers:
                - name: c2
                  image: oonray/c2
                  securityContext:
                    privileged: true
                  command:
                    - /bin/sh
                  tty: true
                  stdin: true
                  env:
                    - name: USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: vpn-pass
                          key: USERNAME
                    - name: PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: vpn-pass
                          key: PASSWORD
                  ports:
                    - containerPort: 1337
                    - containerPort: 5000
